network_params:
  input_channel: 1
  output_channel: 256
  hidden_size: 256
  image_height: 442
  image_width: 442
  num_fiducial: 20
  num_class: 11
imgH: 64
lang_list:
         - 'en'
character_list: 0123456789!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~ €ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
